version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: construction-ai-postgres
    restart: always
    environment:
      POSTGRES_DB: construction_ai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
